### PR TITLE
Updating our copy with the latest changes from the upstream

### PR DESCRIPTION
**Pull request by SpencerKaiser**
Just pulling in the latest updates from the upstream repo

### CODE REVIEW

**Comment by SpencerKaiser** [comment]
@AmericanAirlines/backstage anyone have any concerns with updating this? I saw a small tweak I wanted to make to their docs and realized we're way far behind...

**Comment by MelindaMalmgren** [comment]
I say go for it 👍

**Review by MelindaMalmgren — APPROVED** [review]

**Review by karlhaworth — APPROVED** [review]
Lgtm

**Comment by karlhaworth** [comment]
I’d stay more on top of this if we had stuff we were contributing… we haven’t yet. Guide me if I need to change habits @SpencerKaiser

**Pull request merged**
